### ISSUE TITLE
Rate limited! Please try again later.

### ISSUE THREAD

**Issue by DudeNin64** [ztjhz/FreeChatGPT#100]
Ok, so I was using it just fine with my own api key, and now it's giving me this error all the time, even on messages that worked before.
I tried reducing the max tokens to 2000 ish, but then it gave me incomplete answers.

![Screenshot_48](https://user-images.githubusercontent.com/40683155/226163968-ef6477ec-4b93-4569-9409-84d3fe70a0c0.png)

**Comment by PlaneAdhi03** [comment]
Same error for me too, Only after changing the `max_token` I am getting this, I think the values gets added cumulatively when we change the slider, Thus exceeding the max limit

**Comment by Yardanico** [comment]
@ztjhz I'm still seeing max_tokens being at 4000 by default when creating new chats on https://freechatgpt.chat/, is it just because the new version wasn't deployed yet?

**Comment by ztjhz** [comment]
The issue has been resolved and the updated code has been deployed. It's worth noting that the 'max_tokens' parameter specifies the maximum number of input tokens allowed, which in this case is 4000. This fix addresses the original bug as intended.

**Comment by Yardanico** [comment]
@ztjhz ah, it looks like there's just a difference between the UI and the code now. 
By default max_tokens in new chats looks like this:
![image](https://user-images.githubusercontent.com/21169548/226238757-68b86452-9b51-40ab-895d-3edb88f8e7d4.png)

But when the requests are sent, max_tokens is set to null
![image](https://user-images.githubusercontent.com/21169548/226238795-445a4910-433b-417f-ac5c-e1a264765027.png)

**Comment by ztjhz** [comment]
This is an intended change because we want the users to be able to limit their input tokens, not the model tokens. We will definitely be implementing a feature to allow users to change their default model parameters.
