### ISSUE TITLE
local deployment failed at npm run dev

### ISSUE THREAD

**Issue by aopaw** [ztjhz/FreeChatGPT#107]
Hello,
I at the beginning have this error:
Error: The specified module could not be found.
@swc\core-win32-x64-msvc\swc.win32-x64-msvc.node

Following this one https://stackoverflow.com/questions/69859120/the-specified-module-could-not-be-found-d-next-js-firstapp-node-modules-n
I install the microsoft redist package, and the error no longer comes out. 

But it still failed when running it.

PS D:\gpt\FreeChatGPT> npm run dev

> chatgpt-free-app@0.0.0 dev D:\gpt\FreeChatGPT
> vite

file:///D:/gpt/FreeChatGPT/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
[90m    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)[39m
[90m    at async link (internal/modules/esm/module_job.js:37:21)[39m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chatgpt-free-app@0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chatgpt-free-app@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2023-03-21T04_22_37_340Z-debug.log

**Comment by ayaka14732** [comment]
You may need to upgrade your Node.js version if it is outdated.

**Comment by aopaw** [comment]
> You may need to upgrade your Node.js version if it is outdated.

It works now. Thank you.
