### ISSUE TITLE
{"error":"No API keys found"} Rate limited! Please try again later.

### ISSUE THREAD

**Issue by Mccranky83** [ztjhz/FreeChatGPT#111]
I get that the GPT-4 is cutting back on the queries you're allowed to send per minute, only, I've been waiting since yesterday and I'm still getting this popup warning so I'm feeling a bit anxious. Is every thing all right?

**Comment by Mccranky83** [comment]
> > I get that the GPT-4 is cutting back on the queries you're allowed to send per minute, only, I've been waiting since yesterday and I'm still getting this popup warning so I'm feeling a bit anxious. Is every thing all right?
> 
> Because you should get the API for GPT-4 and the free API may not work. However, you can try gpt-3.5-turbo by you own API.

I switched to the gpt-3.5-turbo model and `https://sharegpt.churchless.tech/share/v1/chat` endpoint, but now I get this instead:
```
OpenAI API responded:

{
    "error": {
        "message": "Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.",
        "type": "access_terminated",
        "param": null,
        "code": null
    }
}

Rate limited! Please try again later.
```

**Comment by whitemankpi** [comment]
getting the same error in  gpt-3.5-turbo model with personal API key

**Comment by AXYZdong** [comment]
> getting the same error in gpt-3.5-turbo model with personal API key

It can work on my own web : https://axyzdong.github.io/FreeChatGPT/

You can try it !

![image](https://user-images.githubusercontent.com/45477220/226913788-f927b714-4d7b-4a55-93b3-f1f61da024b9.png)
