### ISSUE TITLE
Feature Request: Option to hide system prompts

### ISSUE THREAD

**Issue by beornf** [ztjhz/FreeChatGPT#118]
Could there be a UI option where the system prompts are hidden from the main chat window and moved to the chat configuration. Since when looking through your history it's not always necessary to know the prompt details unless you are adding one to the prompt library.

**Comment by ayaka14732** [comment]
I believe that the system prompt should not be hidden. It is actually very useful, and customising the system prompt is heavily used in "jailbreaking" and prompt engineering. We should not hide this useful information.

**Comment by beornf** [comment]
Yeah I might have been overthinking this a little. Thanks for the project!
