### ISSUE TITLE
feature: Add Prompt Library

### ISSUE THREAD

**Issue by saliksik** [ztjhz/FreeChatGPT#32]
Can we add a prompt library (localstorage) just like this? and a button for continue writing function.

![Web capture_7-3-2023_01234_chat openai com](https://user-images.githubusercontent.com/122975898/223167247-66dce399-dc4b-4324-8795-c8483be74791.jpeg)

**Comment by huangjunxin** [comment]
Although it may not be relevant to this issue, I would like to ask whether the prompts in AIPRM are **NOT** open source? Thank you very much.

**Comment by ztjhz** [comment]
We have added a prompt library!
