### ISSUE TITLE
bug: cannot work with subpage

### ISSUE THREAD

**Issue by tshu-w** [ztjhz/FreeChatGPT#64]
I got `Disallowed MIME type (“text/html”) error` and a blank page if I visited the [GitHub page domain](https://tshu-w.github.io/ChatGPTApp/). Everything works fine If I bind a custom domain.

**Comment by ztjhz** [comment]
When using a subpage, please ensure to set the correct `base` in `vite.config.js`. By default, `base` is set to `/`, so you'll need to update it for subpages. For example, if you're deploying to `https://<USERNAME>.github.io/<REPO>`, set the `base` to `/REPO/`.

To make things easier, here's the code you can use in your `vite.config.js` file:

```js
export default defineConfig({
  base: '/REPO/'
.
.
.
```

We'll also update the deployment instructions in the readme to reflect this change.

**Comment by tshu-w** [comment]
@ztjhz Hi, thanks for your quick reply. I have no knowledge of front-end development, but I'm wondering if there are any methods like https://stackoverflow.com/a/59576343/18118915 that don't require users to make changes.

**Comment by Mxililoves** [comment]
I had the same issue after creating another template from a working project.
To fix it I had to change Workflow permission through Repo -> Settings -> Actions -> General
Set:
Read and write permissions
Check:
Allow Github Actions to create and approve pull requests

**Comment by ztjhz** [comment]
> When using a subpage, please ensure to set the correct `base` in `vite.config.js`. By default, `base` is set to `/`, so you'll need to update it for subpages. For example, if you're deploying to `https://<USERNAME>.github.io/<REPO>`, set the `base` to `/REPO/`.
> 
> To make things easier, here's the code you can use in your `vite.config.js` file:
> 
> ```js
> export default defineConfig({
>   base: '/REPO/'
> .
> .
> .
> ```
> 
> We'll also update the deployment instructions in the readme to reflect this change.

Have you done this?

**Comment by tshu-w** [comment]
As I mentioned above, this [PR](https://github.com/ztjhz/FreeChatGPT/pull/90) should be a one-time solution.

**Comment by ztjhz** [comment]
Got it, thanks!

**Comment by JiaxiangBU** [comment]
> > When using a subpage, please ensure to set the correct `base` in `vite.config.js`. By default, `base` is set to `/`, so you'll need to update it for subpages. For example, if you're deploying to `https://<USERNAME>.github.io/<REPO>`, set the `base` to `/REPO/`.
> > To make things easier, here's the code you can use in your `vite.config.js` file:
> > ```js
> > export default defineConfig({
> >   base: '/REPO/'
> > .
> > .
> > .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We'll also update the deployment instructions in the readme to reflect this change.
> 
> Have you done this?

Yes, I have set the correct `base` in `vite.config.js` when I used `FreeChatGPT` in the JS file. Also, @akira0245 will update the deployment instructions in the readme to reflect this change(https://github.com/ayaka14732/ChatGPTAPIFree/issues/43#issuecomment-1480641950), as mentioned in the issue thread. Thank you for your support.
