### ISSUE TITLE
[Feature request]Add proxy configuration to the project.

### ISSUE THREAD

**Issue by Mxililoves** [ztjhz/FreeChatGPT#73]
Have you considered adding the option to use socket or HTTP proxies in your project? This could be useful for users who are unable to connect directly to openai.com from certain locations.

**Comment by ztjhz** [comment]
In the app's API settings, users have the option to select their preferred endpoint for the API. They can choose from OpenAI's official endpoint or use the [free ChatGPT API endpoint](https://github.com/ayaka14732/ChatGPTAPIFree), which is proxied. Additionally, users can set up their own proxied endpoint by using the repository found at [this link](https://github.com/ayaka14732/ChatGPTAPIFree) and use it instead.

**Comment by ayaka14732** [comment]
https://chatgpt-api.shn.hk/v1/ can act as a proxy. If the user provide their own API key, their key will be used to access the OpenAI API instead of the free key.
