### ISSUE TITLE
is GTP-4 api supported？

### ISSUE THREAD

**Issue by snow8261** [ztjhz/FreeChatGPT#80]
GTP-4 has been released, is GTP-4 api supported?

**Comment by Minority2310** [comment]
> GTP-4 has been released, is GTP-4 api supported?

![image](https://user-images.githubusercontent.com/73096231/225188371-ef103365-156b-438a-a406-d1255a8f3db6.png)

**Comment by Yardanico** [comment]
@snow8261 GPT-4 uses the exact same API structure as gpt-3.5-turbo, so it's only a matter of changing the model name from `gpt-3.5-turbo` to `gpt-4`.

**Comment by ztjhz** [comment]
We plan to introduce a feature that will enable users to select the model to be used for their current chat.
