### ISSUE TITLE
Is it still working? (Quota error)

### ISSUE THREAD

**Issue by Zenesy** [ztjhz/FreeChatGPT#91]
Hello! Really great project! Though I was wondering if it is still working. I'm getting; 
"You exceeded your current quota, please check your plan and billing details.", 

Message from freechatgpt.chat:
Too many request! We recommend changing your API endpoint or API key

error despite creating only about 5 responses in 2 days. I'm using Ayaka's free API Endpoint.

**Comment by AXYZdong** [comment]
you can use your own API

**Comment by Zenesy** [comment]
> you can use your own API

The free api is not working anymore?

**Comment by Zenesy** [comment]
I found out it is because of the API by Ayaka is being too costly. The issue can be closed. Hopefully we can continue supporting this project(s).
