### ISSUE TITLE
Multiple Rounds of Chatting.

### ISSUE THREAD

**Issue by PJYGit** [ztjhz/FreeChatGPT#93]
Haven't read the source code yet, but are you using the open api provided by [API Reference](https://platform.openai.com/docs/api-reference/edits?lang=python)?  I didn't find the parameter which can be used to accomplish multiple rounds chatting. Can I get a brief introduction on how to impl it?

**Comment by ayaka14732** [comment]
Can you elaborate?

**Comment by PJYGit** [comment]
Well, ChatGPT didn't remember the context of the former question. I'm curious on how to tell ChatGPT to remember it using the open API. For example:

_Me: What is the CPC of the information feed advertisement on the e-commerce platform?
ChatGPT: blabla
Me: Is there a difference between different countries?
ChatGPT: ... marriage, tax...._

**Comment by Captain8771** [comment]
perhaps [this one](https://platform.openai.com/docs/api-reference/chat/create)? It seems that the user (you) need to be the one saving messages.

**Comment by ayaka14732** [comment]
I think it is working as expected?

![](https://user-images.githubusercontent.com/68557794/226513350-a9e13399-efc1-40d6-a090-ac29680d0a77.png)

**Comment by PJYGit** [comment]
Yes! The screen shot is correct!
And thank to @Captain8771 , it may solve my problem(but haven't try it yet).

**Comment by PJYGit** [comment]
Here is the chat format: https://platform.openai.com/docs/guides/chat/introduction
