### ISSUE TITLE
Feature: Keep default settings as the default when opening a new conversation

### ISSUE THREAD

**Issue by noelialc** [ztjhz/FreeChatGPT#97]
Right now every time you start a new conversation it defaults to GPT 3.5 and certain temperature, top-p, etc. settings. Perhaps these settings could be saved in localhost so once we save certain settings they get saved as the default for future sessions as well.

**Comment by noelialc** [comment]
Oh I see there's a defaultChatConfig but it doesn't seem to be getting saved.

**Comment by ztjhz** [comment]
defaultChatConfig is currently not being saved / is not editable. We will implement this feature in the future.

**Comment by sagarspatil** [comment]
> defaultChatConfig is currently not being saved / is not editable. We will implement this feature in the future.

Brilliant work. I ⭐️’ed the repo. 
Any ETA on when do you plan to add this feature?
