### ISSUE TITLE
Too many request! We recommend changing your API endpoint or API key

### ISSUE THREAD

**Issue by Ros-ua** [ztjhz/FreeChatGPT#98]
OpenAI API responded:

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

Message from freechatgpt.chat:
Too many request! We recommend changing your API endpoint or API key

**Comment by ztjhz** [comment]
We have added a new api endpoint: https://freechatgpt.chat/
The source code for this endpoint can be found here: https://github.com/acheong08/ShareGPT

**Comment by Mccranky83** [comment]
It works fine now with the new endpoint. Great job with the aspiring project!
